/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package kasir;

import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author naufalsa
 */
public class databarang extends javax.swing.JFrame {
    
    /**
     * Creates new form databarang
     */
    public databarang() {
        initComponents();
        tampilTabel();
        
    }
    
    private void tampilTabel(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama barang");
        model.addColumn("Harga barang");
        model.addColumn("Stok");
        
        try {
            String sql = "select * from barang";
            Connection conn = (Connection)koneksi.configDB();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()){
                model.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4)
                });
            }
            tabelinput.setModel(model);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error",0);
        }
    }
    
    private void pilihData(){
        int baris = tabelinput.getSelectedRow();
        idText.setText(tabelinput.getValueAt(baris, 0).toString());
        namaText.setText(tabelinput.getValueAt(baris, 1).toString());
        hargaText.setText(tabelinput.getValueAt(baris, 2).toString());
        stokText.setText(tabelinput.getValueAt(baris, 3).toString());
    }
    
    private void kosongkanForm(){
        idText.setText(null);
        namaText.setText(null);
        hargaText.setText(null);
        stokText.setText(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namaText = new javax.swing.JTextField();
        idText = new javax.swing.JTextField();
        hargaText = new javax.swing.JTextField();
        stokText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelinput = new javax.swing.JTable();
        bsimpan = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("NAMA BARANG");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 210, 160, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("ID BARANG");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 170, 130, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("HARGA BARANG");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 260, 180, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("STOK");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 300, 110, 29);

        namaText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(namaText);
        namaText.setBounds(240, 210, 130, 30);

        idText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(idText);
        idText.setBounds(240, 170, 130, 30);

        hargaText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(hargaText);
        hargaText.setBounds(240, 250, 130, 30);

        stokText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(stokText);
        stokText.setBounds(240, 290, 130, 30);

        tabelinput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelinput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelinputMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelinput);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 390, 452, 96);

        bsimpan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bsimpan);
        bsimpan.setBounds(440, 170, 100, 31);

        bhapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        getContentPane().add(bhapus);
        bhapus.setBounds(440, 230, 100, 31);

        bedit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bedit.setText("EDIT");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        getContentPane().add(bedit);
        bedit.setBounds(440, 290, 100, 31);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(440, 110, 100, 31);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 70, 560, 490);

        jPanel2.setBackground(new java.awt.Color(51, 0, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TABEL BARANG TOKO VIA");
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 560, 70);
        getContentPane().add(jPanel4);
        jPanel4.setBounds(410, 80, 140, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        menuutama au = new menuutama();
        au.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        try {
            String sql = "delete from barang where id_barang = "+idText.getText();
            Connection conn = (Connection)koneksi.configDB();
            PreparedStatement pst=conn.prepareStatement(sql);
            Object[] tombol = {"Ya","Tidak"};
            int yatidak = JOptionPane.showOptionDialog(null, "Anda yakin ingin menghapus data ini?", "Konfirmasi hapus",
                    0, 2, null, tombol, tombol[1]);
            if(yatidak == JOptionPane.NO_OPTION){
                this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            } else if(yatidak == JOptionPane.YES_OPTION){
                pst.execute();
                conn.prepareStatement("ALTER TABLE barang DROP id_barang").execute();
                conn.prepareStatement("ALTER TABLE barang ADD id_barang INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST").execute();
                tampilTabel();
                kosongkanForm();
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data:\n"+e.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_bhapusActionPerformed
    
    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorAdded

    private void tabelinputMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelinputMouseReleased
        // TODO add your handling code here:
        pilihData();
    }//GEN-LAST:event_tabelinputMouseReleased

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        try {
            String sql = "insert into barang (nama_barang, harga, stok) values"
                    + "('"+namaText.getText()+"', "
                    + hargaText.getText() +", "
                    + stokText.getText() + ")";
            Connection conn=(Connection)koneksi.configDB();
            PreparedStatement pst=conn.prepareStatement(sql);
            conn.prepareStatement("ALTER TABLE barang AUTO_INCREMENT=0").execute();
            pst.execute();
            tampilTabel();
            JOptionPane.showInternalMessageDialog(null, "Data berhasil disimpan.", "Sukses", 1);
            kosongkanForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Data gagal disimpan:\n"+e.getMessage(), "Error", 0);
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        try {
            String sql = "update barang set nama_barang = '" + namaText.getText() + "', "
                    + "harga = '" + hargaText.getText() + "', "
                    + "stok = '" + stokText.getText() + "'"
                    + "where id_barang = '" + idText.getText() + "'";
            Connection conn=(Connection)koneksi.configDB();
            PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            tampilTabel();
            JOptionPane.showInternalMessageDialog(null, "Data berhasil diedit.", "Sukses", 1);
            kosongkanForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal mengedit data:\n"+e.getMessage(),"Error",0);
        }
    }//GEN-LAST:event_beditActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(databarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(databarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(databarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(databarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new databarang().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bsimpan;
    private javax.swing.JTextField hargaText;
    private javax.swing.JTextField idText;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namaText;
    private javax.swing.JTextField stokText;
    private javax.swing.JTable tabelinput;
    // End of variables declaration//GEN-END:variables
}
